import Header from "@/components/main-page/main-header/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Time To Go!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
            {children}
      </body>
    </html>
  );
}
