import { db } from "./firebase"; // Import Firestore instance
import { collection, setDoc, doc } from "firebase/firestore";

const destinationsData= {
  "sof_sof": {
      "airport": "Sofia International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Sofia",
      "counter": 0,
      "country": "Bulgaria",
      "description": "Sofia, Bulgaria’s vibrant capital, is a city where history meets modernity. Start your journey at Alexander Nevsky Cathedral, one of the largest Orthodox churches in the world, with its golden domes and intricate frescoes. Vitosha Boulevard is the perfect place for shopping and dining, offering stunning views of Vitosha Mountain. The ancient Roman ruins of Serdica, located beneath the city, tell the story of Sofia’s past. Don’t miss the Boyana Church, a UNESCO-listed site with remarkable medieval frescoes. For outdoor enthusiasts, a trip to Vitosha Mountain offers great hiking and skiing opportunities just a short drive from the city. The National Palace of Culture hosts concerts, exhibitions, and cultural events throughout the year.",
      "iaco": "LBSF",
      "iata": "SOF",
      "id": "sof_sof",
      "img": "https://images.unsplash.com/photo-1519429753079-3b0f0a95dea8?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "42.6975",
      "longitude": "23.3242",
      "temperature": "cold",
      "type": "city"
    },
    "plo_pdv": {
      "airport": "Plovdiv Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Plovdiv",
      "counter": 0,
      "country": "Bulgaria",
      "description": "Plovdiv, one of the oldest cities in Europe, offers a mix of ancient history and modern charm. The Old Town is a maze of cobblestone streets, colorful houses, and well-preserved Roman ruins. The Ancient Roman Theatre, dating back to the 2nd century AD, still hosts concerts and performances today. Explore the vibrant Kapana district, an artsy neighborhood filled with galleries, cafés, and craft shops. The city’s seven hills offer stunning panoramic views, with Nebet Tepe being the best spot for sunset. Plovdiv’s relaxed atmosphere, combined with its cultural richness, makes it a must-visit destination in Bulgaria.",
      "iaco": "LBPD",
      "iata": "PDV",
      "id": "plo_pdv",
      "img": "https://images.unsplash.com/photo-1633210181101-774c588bc997?q=80&w=3077&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "42.1354",
      "longitude": "24.7453",
      "temperature": "moderate",
      "type": "historical"
    },
    "ban_sof": {
      "airport": "Sofia International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Bansko",
      "counter": 0,
      "country": "Bulgaria",
      "description": "Bansko is Bulgaria’s top ski resort, attracting winter sports enthusiasts from all over Europe. Located in the Pirin Mountains, Bansko offers well-maintained ski slopes, cozy mountain lodges, and an après-ski scene with lively bars and traditional taverns. The town itself is rich in history, featuring cobbled streets and stone houses dating back to the Bulgarian Revival period. The Holy Trinity Church, with its striking bell tower, is a must-visit. In summer, Bansko turns into a paradise for hikers and nature lovers, with scenic trails leading to crystal-clear lakes and panoramic peaks in Pirin National Park.",
      "iaco": "LBSF",
      "iata": "SOF",
      "id": "ban_sof",
      "img": "https://images.unsplash.com/photo-1547131274-409e136f7c3a?q=80&w=3024&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "41.8389",
      "longitude": "23.4883",
      "temperature": "cold",
      "type": "snowy"
    },
    "var_var": {
      "airport": "Varna Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Varna",
      "counter": 0,
      "country": "Bulgaria",
      "description": "Varna, known as the 'Sea Capital of Bulgaria,' is a stunning coastal city on the Black Sea. The city is famous for its golden sandy beaches, lively nightlife, and historical landmarks. The Sea Garden, a vast park along the coastline, is perfect for a leisurely walk or a picnic. Visit the Varna Archaeological Museum to see the world’s oldest known gold treasure, dating back over 6,000 years. The Aladzha Monastery, a medieval cave monastery carved into limestone cliffs, offers a glimpse into Bulgaria’s religious history. Nearby, the Stone Forest, a natural rock formation, provides a surreal landscape to explore. Whether you're looking to relax on the beach or immerse yourself in history, Varna has something for everyone.",
      "iaco": "LBWN",
      "iata": "VAR",
      "id": "var_var",
      "img": "https://images.unsplash.com/photo-1615835684430-5935018b8fed?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "43.2141",
      "longitude": "27.9147",
      "temperature": "moderate",
      "type": "beach"
    },
    "sie_rep": {
      "airport": "Siem Reap International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Siem Reap",
      "counter": 0,
      "country": "Cambodia",
      "description": "Siem Reap is the gateway to the world-famous Angkor Wat, a UNESCO World Heritage Site and the largest religious monument on Earth. Explore the sprawling temple complex, from the towering stone faces of Bayon Temple to the jungle-covered ruins of Ta Prohm. Beyond temples, visit the vibrant Pub Street for lively nightlife, street food, and cultural performances. The floating villages of Tonlé Sap Lake offer a glimpse into local life, while the Angkor National Museum provides deep historical insights. Take a countryside tour to see rice fields, lotus farms, and traditional Khmer villages. Siem Reap is a perfect mix of ancient wonders and modern entertainment.",
      "iaco": "VDSR",
      "iata": "REP",
      "id": "sie_rep",
      "img": "https://images.unsplash.com/photo-1606231140504-b6ec6cbbbf6b?q=80&w=2433&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "13.4125",
      "longitude": "103.8670",
      "temperature": "hot",
      "type": "historical"
    },
    "phn_pnh": {
      "airport": "Phnom Penh International Airport",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Phnom Penh",
      "counter": 0,
      "country": "Cambodia",
      "description": "Phnom Penh, Cambodia’s bustling capital, is a city rich in history and culture. Visit the Royal Palace, home to the stunning Silver Pagoda adorned with thousands of silver tiles. The National Museum showcases Khmer artifacts, while Wat Phnom, a hilltop temple, offers panoramic city views. The Tuol Sleng Genocide Museum and Killing Fields provide a sobering look into Cambodia’s tragic past. Take a sunset cruise on the Mekong River for breathtaking views of the city skyline. The lively Russian Market and Central Market are great for shopping and trying local delicacies. Phnom Penh is a mix of history, resilience, and vibrant city life.",
      "iaco": "VDPP",
      "iata": "PNH",
      "id": "phn_pnh",
      "img": "https://images.unsplash.com/photo-1594444406267-35a7730c6867?q=80&w=3169&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "11.5564",
      "longitude": "104.9282",
      "temperature": "hot",
      "type": "city"
    },
    "koh_kos": {
      "airport": "Sihanoukville International Airport",
      "average_cost": "budget",
      "best_season": "summer",
      "city": "Koh Rong",
      "counter": 0,
      "country": "Cambodia",
      "description": "Koh Rong is a tropical paradise known for its white sandy beaches, crystal-clear waters, and vibrant marine life. Long Set Beach is perfect for relaxation, while Sok San Beach offers a peaceful escape. Adventure seekers can enjoy snorkeling, scuba diving, and jungle trekking. The bioluminescent plankton create a magical glow in the water at night. The island has a mix of lively beach bars and quiet retreats, making it ideal for both party lovers and those seeking tranquility. Nearby, Koh Rong Samloem provides an even more secluded island experience with pristine nature and luxurious eco-resorts.",
      "iaco": "VDSV",
      "iata": "KOS",
      "id": "koh_kos",
      "img": "https://images.unsplash.com/photo-1580277585631-9fbb08d1a6cc?q=80&w=2944&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "10.7255",
      "longitude": "103.2325",
      "temperature": "hot",
      "type": "island"
    },
    "tor_yyz": {
      "airport": "Toronto Pearson International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Toronto",
      "counter": 0,
      "country": "Canada",
      "description": "Toronto, Canada’s largest city, is a vibrant metropolis offering everything from iconic landmarks to multicultural neighborhoods. The CN Tower provides breathtaking panoramic views, while Ripley’s Aquarium and the Royal Ontario Museum are must-visit attractions. Explore the historic Distillery District for unique shops and art galleries. Kensington Market and St. Lawrence Market offer diverse culinary experiences. Take a ferry to the Toronto Islands for outdoor adventures and scenic skyline views. For sports fans, catch a game at the Scotiabank Arena or Rogers Centre. Just outside the city, visit Niagara Falls for one of the most spectacular natural wonders in the world.",
      "iaco": "CYYZ",
      "iata": "YYZ",
      "id": "tor_yyz",
      "img": "https://images.unsplash.com/photo-1517935706615-2717063c2225?q=80&w=2890&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "43.7001",
      "longitude": "-79.4163",
      "temperature": "moderate",
      "type": "city"
    },
    "van_yvr": {
      "airport": "Vancouver International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Vancouver",
      "counter": 0,
      "country": "Canada",
      "description": "Vancouver is a paradise for nature lovers and urban explorers alike. Stanley Park, one of the largest urban parks in the world, offers scenic bike rides along the Seawall. Grouse Mountain provides hiking trails and breathtaking views, while Capilano Suspension Bridge lets you walk through the treetops. Granville Island is a hub for arts, food markets, and live performances. Visit Gastown for historic charm and trendy restaurants. Whale watching tours from the harbor offer a chance to see orcas and dolphins. Nearby, Whistler is a perfect getaway for skiing in the winter and mountain biking in the summer.",
      "iaco": "CYVR",
      "iata": "YVR",
      "id": "van_yvr",
      "img": "https://images.unsplash.com/photo-1559511260-66a654ae982a?q=80&w=3018&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "49.2827",
      "longitude": "-123.1207",
      "temperature": "moderate",
      "type": "city"
    },
    "mon_yul": {
      "airport": "Montréal-Pierre Elliott Trudeau International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Montreal",
      "counter": 0,
      "country": "Canada",
      "description": "Montreal blends European charm with North American modernity. Walk through Old Montreal to see cobblestone streets, historic buildings, and the stunning Notre-Dame Basilica. The Mount Royal Park viewpoint offers spectacular views of the city. Enjoy the world-famous poutine, bagels, and other French-Canadian delicacies. The Montreal Museum of Fine Arts and the Biodome are cultural highlights. In summer, the city comes alive with the International Jazz Festival and Just for Laughs comedy festival. Winter transforms Montreal into a snowy wonderland with Christmas markets, ice skating at Old Port, and cozy cafes serving maple-infused treats.",
      "iaco": "CYUL",
      "iata": "YUL",
      "id": "mon_yul",
      "img": "https://images.unsplash.com/photo-1519178251-5390a0fb6a3f?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "45.5017",
      "longitude": "-73.5673",
      "temperature": "cold",
      "type": "city"
    },
    "ban_yyc": {
      "airport": "Calgary International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Banff",
      "counter": 0,
      "country": "Canada",
      "description": "Banff is Canada’s premier mountain getaway, nestled in the heart of the Rockies. The turquoise waters of Lake Louise and Moraine Lake are picture-perfect destinations for canoeing and hiking. Banff National Park offers breathtaking scenery, abundant wildlife, and trails leading to hidden waterfalls and glaciers. The Banff Gondola takes you to the top of Sulphur Mountain for a panoramic view of the surrounding peaks. The town itself is home to cozy lodges, boutique shops, and hot springs. In winter, Banff becomes a world-class skiing and snowboarding destination.",
      "iaco": "CYYC",
      "iata": "YYC",
      "id": "ban_yyc",
      "img": "https://images.unsplash.com/photo-1561134643-668f9057cce4?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "51.1784",
      "longitude": "-115.5708",
      "temperature": "cold",
      "type": "mountain"
    },
    "que_yqb": {
      "airport": "Québec City Jean Lesage International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Quebec City",
      "counter": 0,
      "country": "Canada",
      "description": "Quebec City is like stepping into a European fairytale. The charming Old Town, a UNESCO World Heritage Site, is home to cobblestone streets, quaint shops, and the majestic Château Frontenac. Walk along the historic city walls, explore Place Royale, and admire Montmorency Falls, which are taller than Niagara Falls. During winter, the city transforms into a magical wonderland with its famous Winter Carnival featuring ice palaces, parades, and outdoor festivities. Enjoy authentic French cuisine at cozy bistros and sip on maple-infused treats.",
      "iaco": "CYQB",
      "iata": "YQB",
      "id": "que_yqb",
      "img": "https://images.unsplash.com/photo-1558486517-1025f6d30fc3?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "46.8139",
      "longitude": "-71.2082",
      "temperature": "cold",
      "type": "historical"
    },
    "whi_yvr": {
      "airport": "Vancouver International Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Whistler",
      "counter": 0,
      "country": "Canada",
      "description": "Whistler is Canada’s top ski resort, known for its world-class slopes, charming alpine village, and breathtaking mountain views. Ski or snowboard on Whistler and Blackcomb mountains, or take the Peak 2 Peak Gondola for stunning aerial views. In summer, enjoy hiking, mountain biking, and zip-lining through the lush forests. The pedestrian-friendly village is filled with boutique shops, gourmet restaurants, and lively bars. The Scandinave Spa offers the perfect relaxation after an adventurous day. Just a 2-hour drive from Vancouver, Whistler is an all-season adventure paradise.",
      "iaco": "CYVR",
      "iata": "YVR",
      "id": "whi_yvr",
      "img": "https://images.unsplash.com/photo-1581258308608-279198249e38?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "50.1163",
      "longitude": "-122.9574",
      "temperature": "cold",
      "type": "snowy"
    },
    "san_scl": {
      "airport": "Comodoro Arturo Merino Benítez International Airport",
      "average_cost": "mid",
      "best_season": "spring",
      "city": "Santiago",
      "counter": 0,
      "country": "Chile",
      "description": "Santiago, Chile’s bustling capital, is a vibrant blend of colonial history and modern city life, set against the breathtaking backdrop of the Andes Mountains. Start your journey at Plaza de Armas, the historic heart of the city, where you’ll find Santiago Metropolitan Cathedral and the National History Museum. Take a cable car up Cerro San Cristóbal for panoramic views of the city. The bohemian neighborhoods of Bellavista and Lastarria are filled with colorful street art, trendy cafés, and live music venues. Wine lovers can take a short trip to the Maipo Valley, Chile’s famous wine region, to sample world-class reds. Just a few hours away, you can explore Valparaíso’s colorful hillside streets or head to the Andes for skiing in winter.",
      "iaco": "SCEL",
      "iata": "SCL",
      "id": "san_scl",
      "img": "https://images.unsplash.com/photo-1593985437133-03d5e1435c03?q=80&w=3133&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-33.4489",
      "longitude": "-70.6693",
      "temperature": "moderate",
      "type": "city"
    },
    "val_vap": {
      "airport": "Aeropuerto Torquemada",
      "average_cost": "budget",
      "best_season": "summer",
      "city": "Valparaíso",
      "counter": 0,
      "country": "Chile",
      "description": "Valparaíso, Chile’s most artistic city, is known for its colorful hillside homes, funiculars, and bohemian atmosphere. Wander through the steep, graffiti-covered streets of Cerro Alegre and Cerro Concepción, where you’ll find boutique shops, street performers, and vibrant murals. Take a historic funicular ride for stunning ocean views. Visit La Sebastiana, the quirky home of Nobel Prize-winning poet Pablo Neruda. The bustling port is great for seafood lovers, with local markets serving fresh ceviche and empanadas. Nightlife in Valparaíso is lively, with rooftop bars offering breathtaking views of the Pacific Ocean.",
      "iaco": "SCVM",
      "iata": "VAP",
      "id": "val_vap",
      "img": "https://images.unsplash.com/photo-1517956918805-bbacc31d5f81?q=80&w=2954&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-33.0472",
      "longitude": "-71.6127",
      "temperature": "moderate",
      "type": "historical"
    },
    "ata_cpo": {
      "airport": "Desierto de Atacama Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Atacama Desert",
      "counter": 0,
      "country": "Chile",
      "description": "The Atacama Desert, the driest desert on Earth, offers some of the most surreal landscapes in the world. Visit the Moon Valley (Valle de la Luna) to witness breathtaking rock formations and salt flats that look like another planet. The El Tatio Geysers provide an incredible sunrise spectacle, with steaming geothermal vents surrounded by the Andean mountains. Stargazing in Atacama is world-renowned, thanks to the region’s clear skies—visit the ALMA Observatory for an unforgettable view of the universe. Adventurers can go sandboarding in the dunes or explore the salt flats of Laguna Cejar.",
      "iaco": "SCAT",
      "iata": "CPO",
      "id": "ata_cpo",
      "img": "https://images.unsplash.com/photo-1556741495-4a9f3c6935e8?q=80&w=2819&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-24.5000",
      "longitude": "-69.2500",
      "temperature": "hot",
      "type": "desert"
    },
    "pun_puq": {
      "airport": "Presidente Carlos Ibáñez del Campo International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Punta Arenas",
      "counter": 0,
      "country": "Chile",
      "description": "Punta Arenas is the gateway to Patagonia and Antarctica, offering rugged landscapes, penguin colonies, and historic sites. Visit the Magdalena Island Penguin Reserve to see thousands of Magellanic penguins in their natural habitat. Explore the Strait of Magellan and learn about its rich maritime history at the Nao Victoria Museum. The Torres del Paine National Park, just a short trip away, is one of the world’s best trekking destinations, featuring dramatic mountains, glaciers, and pristine lakes. Don’t forget to try the local king crab dish, centolla, a specialty of the region.",
      "iaco": "SCCI",
      "iata": "PUQ",
      "id": "pun_puq",
      "img": "https://images.unsplash.com/photo-1585655271646-e926f621ed17?q=80&w=2952&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-53.1638",
      "longitude": "-70.9171",
      "temperature": "cold",
      "type": "snowy"
    },
    "eas_ipc": {
      "airport": "Mataveri International Airport",
      "average_cost": "luxury",
      "best_season": "spring",
      "city": "Easter Island",
      "counter": 0,
      "country": "Chile",
      "description": "Easter Island, one of the most mysterious places on Earth, is famous for its massive stone statues known as Moai. Explore the Rano Raraku quarry, where hundreds of these giant statues were carved. Visit Ahu Tongariki, the most famous row of Moai statues, especially at sunrise. Hike to the Rano Kau crater for breathtaking views of the volcanic caldera and the nearby ceremonial village of Orongo. Anakena Beach offers a rare tropical escape with white sand and turquoise waters. The island’s Polynesian culture, traditional dances, and fresh seafood make it a truly unique travel experience.",
      "iaco": "SCIP",
      "iata": "IPC",
      "id": "eas_ipc",
      "img": "https://images.unsplash.com/photo-1597240890437-6d9c2d4c16aa?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-27.1127",
      "longitude": "-109.3497",
      "temperature": "moderate",
      "type": "island"
    },
    "vie_vte": {
      "airport": "Wattay International Airport",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Vientiane",
      "counter": 0,
      "country": "Laos",
      "description": "Vientiane, the capital of Laos, is a laid-back city with a blend of French colonial charm and Buddhist traditions. Start at the golden Pha That Luang, the most sacred monument in Laos. Visit Wat Sisaket, the oldest temple in Vientiane, home to thousands of Buddha statues. Stroll along the Mekong River promenade at sunset, where you’ll find local markets, street food stalls, and a relaxed atmosphere. The Patuxai Victory Monument, resembling Paris’s Arc de Triomphe, offers panoramic city views. Don’t miss trying Laotian coffee and the famous Laap (minced meat salad) at a riverside café.",
      "iaco": "VLVT",
      "iata": "VTE",
      "id": "vie_vte",
      "img": "https://images.unsplash.com/photo-1602235652477-2b75f983fb9f?q=80&w=3131&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "17.9757",
      "longitude": "102.6331",
      "temperature": "hot",
      "type": "city"
    },
    "lua_lpq": {
      "airport": "Luang Prabang International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Luang Prabang",
      "counter": 0,
      "country": "Laos",
      "description": "Luang Prabang, a UNESCO World Heritage city, is one of the most magical destinations in Southeast Asia. The city is famous for its well-preserved temples, including the stunning Wat Xieng Thong. Wake up early to witness the daily Almsgiving Ceremony, where monks collect offerings from locals. Kuang Si Waterfall, just outside the city, is a breathtaking multi-tiered waterfall with turquoise pools perfect for swimming. A boat ride along the Mekong River takes you to the mysterious Pak Ou Caves, filled with thousands of Buddha statues. The night market offers beautiful handmade crafts and delicious street food like Khao Soi.",
      "iaco": "VLLB",
      "iata": "LPQ",
      "id": "lua_lpq",
      "img": "https://images.unsplash.com/photo-1605126068617-2c7aba682230?q=80&w=2386&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "19.8866",
      "longitude": "102.135",
      "temperature": "moderate",
      "type": "historical"
    },
    "van_vng": {
      "airport": "Vang Vieng Airfield",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Vang Vieng",
      "counter": 0,
      "country": "Laos",
      "description": "Vang Vieng is an adventurer’s paradise, surrounded by dramatic limestone mountains and the Nam Song River. Go tubing or kayaking down the river while enjoying stunning views. Explore the Tham Chang and Tham Phu Kham caves, where you’ll find hidden lagoons and Buddhist shrines. For breathtaking views, hike up to Nam Xay Viewpoint, a perfect spot for sunrise or sunset. Rock climbing and hot air balloon rides offer thrilling perspectives of the landscape. After an active day, relax at a riverside bar with fresh fruit shakes and enjoy the peaceful scenery.",
      "iaco": "VLHS",
      "iata": "VNG",
      "id": "van_vng",
      "img": "https://images.unsplash.com/photo-1562835156-2f62f161b32c?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "18.9233",
      "longitude": "102.4474",
      "temperature": "moderate",
      "type": "mountain"
    },
    "kul_kul": {
      "airport": "Kuala Lumpur International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Kuala Lumpur",
      "counter": 0,
      "country": "Malaysia",
      "description": "Kuala Lumpur, Malaysia’s bustling capital, is a dynamic mix of modern skyscrapers, cultural landmarks, and vibrant street markets. The iconic Petronas Twin Towers offer breathtaking views from the sky bridge. Visit Batu Caves, a Hindu temple set inside a massive limestone cavern. Explore Merdeka Square, Chinatown’s Petaling Street for bargain shopping, and Bukit Bintang’s lively nightlife.",
      "iaco": "WMKK",
      "iata": "KUL",
      "id": "kul_kul",
      "img": "https://images.unsplash.com/photo-1581792343403-f3201559d559?q=80&w=2945&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "3.1390",
      "longitude": "101.6869",
      "temperature": "hot",
      "type": "city"
    },
    "pen_pen": {
      "airport": "Penang International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Penang",
      "counter": 0,
      "country": "Malaysia",
      "description": "Penang, known as the 'Pearl of the Orient,' is a cultural and culinary gem. The historic city of George Town is a UNESCO World Heritage Site filled with colonial buildings and street art. Visit Kek Lok Si Temple, Penang Hill, Batu Ferringhi Beach, and try Penang’s famous street food like Char Kway Teow and Assam Laksa.",
      "iaco": "WMKP",
      "iata": "PEN",
      "id": "pen_pen",
      "img": "https://images.unsplash.com/photo-1597141439895-26b45a8cdd4e?q=80&w=2803&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "5.4164",
      "longitude": "100.3327",
      "temperature": "hot",
      "type": "historical"
    },
    "lan_lgy": {
      "airport": "Langkawi International Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Langkawi",
      "counter": 0,
      "country": "Malaysia",
      "description": "Langkawi is famous for its stunning beaches, rainforests, and duty-free shopping. Ride the Langkawi Sky Bridge for breathtaking views of the Andaman Sea. Relax at Pantai Cenang Beach, explore the mangroves of Kilim Geoforest Park, and take a dip in the Seven Wells Waterfall.",
      "iaco": "WMKL",
      "iata": "LGK",
      "id": "lan_lgy",
      "img": "https://images.unsplash.com/photo-1591251010190-43c22baa46b0?q=80&w=2666&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "6.3260",
      "longitude": "99.8432",
      "temperature": "hot",
      "type": "island"
    },
    "kuc_kch": {
      "airport": "Kuching International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Kuching",
      "counter": 0,
      "country": "Malaysia",
      "description": "Kuching, the capital of Sarawak, is rich in culture and nature. Visit the Sarawak Cultural Village, Kuching Waterfront, and the Semenggoh Wildlife Centre for a chance to see orangutans. Nature lovers can explore Bako National Park, home to proboscis monkeys and rainforest trails.",
      "iaco": "WBGG",
      "iata": "KCH",
      "id": "kuc_kch",
      "img": "https://images.unsplash.com/photo-1603768182862-483aeb564747?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "1.5533",
      "longitude": "110.3592",
      "temperature": "hot",
      "type": "city"
    },
    "kot_bki": {
      "airport": "Kota Kinabalu International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Kota Kinabalu",
      "counter": 0,
      "country": "Malaysia",
      "description": "Kota Kinabalu, the capital of Sabah, is the gateway to Mount Kinabalu, the highest peak in Southeast Asia. Adventure seekers can hike the mountain or explore Kinabalu National Park. Visit Tunku Abdul Rahman Marine Park for snorkeling and diving, and enjoy the sunset at Tanjung Aru Beach.",
      "iaco": "WBKK",
      "iata": "BKI",
      "id": "kot_bki",
      "img": "https://images.unsplash.com/photo-1562595437-7d7d770cd6a6?q=80&w=3125&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "5.9804",
      "longitude": "116.0735",
      "temperature": "hot",
      "type": "beach"
    },
    "cam_iph": {
      "airport": "Sultan Azlan Shah Airport",
      "average_cost": "budget",
      "best_season": "summer",
      "city": "Cameron Highlands",
      "counter": 0,
      "country": "Malaysia",
      "description": "Cameron Highlands is Malaysia’s most famous hill station, known for its cool climate, rolling tea plantations, and strawberry farms. Visit the famous Boh Tea Plantation for breathtaking views, and explore the Mossy Forest, a mystical, cloud-covered jungle. Enjoy fresh strawberries at local farms and visit the Cameron Lavender Garden for colorful floral displays. Hiking trails lead through beautiful landscapes, while the Time Tunnel Museum offers insights into the region’s colonial past.",
      "iaco": "WMKI",
      "iata": "IPH",
      "id": "cam_iph",
      "img": "https://images.unsplash.com/photo-1604631715696-5ba4c27d021f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "4.4904",
      "longitude": "101.3896",
      "temperature": "moderate",
      "type": "mountain"
    },
    "jak_cgk": {
      "airport": "Soekarno-Hatta International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Jakarta",
      "counter": 0,
      "country": "Indonesia",
      "description": "Jakarta, Indonesia's bustling capital, is a dynamic mix of modern skyscrapers, historic sites, and vibrant street markets. Explore the iconic National Monument (Monas), the colonial-style Kota Tua (Old Town), and the Istiqlal Mosque, the largest in Southeast Asia. Shop at Grand Indonesia Mall, experience local cuisine at Menteng, or take a boat to the Thousand Islands for a beach escape.",
      "iaco": "WIII",
      "iata": "CGK",
      "id": "jak_cgk",
      "img": "https://images.unsplash.com/photo-1567756396406-f529ebb5583d?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-6.2088",
      "longitude": "106.8456",
      "temperature": "hot",
      "type": "city"
    },
    "bal_dps": {
      "airport": "Ngurah Rai International Airport",
      "average_cost": "luxury",
      "best_season": "summer",
      "city": "Bali",
      "counter": 0,
      "country": "Indonesia",
      "description": "Bali is Indonesia’s most famous island paradise, offering a mix of stunning beaches, lush rice terraces, and vibrant culture. Visit Ubud for traditional arts, explore Uluwatu Temple for cliffside views, and relax in Seminyak’s luxury resorts. The beaches of Nusa Dua, the waterfalls of Munduk, and the nightlife in Kuta make Bali a top destination.",
      "iaco": "WADD",
      "iata": "DPS",
      "id": "bal_dps",
      "img": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2977&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-8.4095",
      "longitude": "115.1889",
      "temperature": "hot",
      "type": "island"
    },
    "yog_jog": {
      "airport": "Adisutjipto International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Yogyakarta",
      "counter": 0,
      "country": "Indonesia",
      "description": "Yogyakarta is the cultural heart of Java, known for its historical sites and rich Javanese heritage. Visit the majestic Borobudur and Prambanan temples, explore the Sultan’s Palace, and wander through Malioboro Street’s lively markets. Nature lovers can visit Jomblang Cave or hike up Mount Merapi for a thrilling adventure.",
      "iaco": "WARJ",
      "iata": "JOG",
      "id": "yog_jog",
      "img": "https://images.unsplash.com/photo-1578469550956-0e16b69c6a3d?q=80&w=3206&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-7.7956",
      "longitude": "110.3695",
      "temperature": "hot",
      "type": "historical"
    },
    "lab_lbj": {
      "airport": "Komodo Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Labuan Bajo",
      "counter": 0,
      "country": "Indonesia",
      "description": "Labuan Bajo is the gateway to the stunning Komodo National Park, home to the legendary Komodo dragons. Take a boat tour to Pink Beach, snorkel in the crystal-clear waters of Kanawa Island, or hike Padar Island for breathtaking views. The diving spots here are among the best in the world, teeming with manta rays and vibrant marine life.",
      "iaco": "WATO",
      "iata": "LBJ",
      "id": "kom_lbj",
      "img": "https://images.unsplash.com/photo-1589309736404-2e142a2acdf0?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-8.4960",
      "longitude": "119.8870",
      "temperature": "hot",
      "type": "island"
    },
    "lom_lop": {
      "airport": "Lombok International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Lombok",
      "counter": 0,
      "country": "Indonesia",
      "description": "Lombok is an unspoiled paradise with beautiful beaches, scenic mountains, and fewer crowds than Bali. Trek up Mount Rinjani for an epic sunrise, relax on the Gili Islands, or surf at Kuta Lombok. The island also has hidden waterfalls like Tiu Kelep and Benang Stokel for nature lovers.",
      "iaco": "WADL",
      "iata": "LOP",
      "id": "lom_lop",
      "img": "https://plus.unsplash.com/premium_photo-1664117436445-76133b33b07a?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "-8.6520",
      "longitude": "116.3249",
      "temperature": "hot",
      "type": "island"
    },
    "chi_cnx": {
      "airport": "Chiang Mai International Airport",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Chiang Mai",
      "counter": 0,
      "country": "Thailand",
      "description": "Chiang Mai is Thailand’s cultural hub, surrounded by mountains and ancient temples. Visit Wat Phra That Doi Suthep for panoramic city views, explore the Old City’s temples, and participate in a monk chat. Chiang Mai is famous for its Yi Peng Lantern Festival, night bazaars, and elephant sanctuaries. Take a day trip to Doi Inthanon National Park for waterfalls and Thailand’s highest peak.",
      "iaco": "VTCC",
      "iata": "CNX",
      "id": "chi_cnx",
      "img": "https://plus.unsplash.com/premium_photo-1661929242720-140374d97c94?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "18.7883",
      "longitude": "98.9853",
      "temperature": "moderate",
      "type": "historical"
    },
    "phu_hkt": {
      "airport": "Phuket International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Phuket",
      "counter": 0,
      "country": "Thailand",
      "description": "Phuket is Thailand’s largest island, offering stunning beaches, vibrant nightlife, and exciting adventures. Relax on Patong Beach, take a boat tour to the famous Phi Phi Islands, or snorkel in the crystal-clear waters of Similan Islands. Visit Big Buddha, explore Phuket Old Town’s colonial streets, and enjoy the lively Bangla Road.",
      "iaco": "VTSP",
      "iata": "HKT",
      "id": "phu_hkt",
      "img": "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?q=80&w=3201&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "7.8804",
      "longitude": "98.3923",
      "temperature": "hot",
      "type": "beach"
    },
    "kra_kbv": {
      "airport": "Krabi International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Krabi",
      "counter": 0,
      "country": "Thailand",
      "description": "Krabi is a paradise for beach lovers and adventure seekers. Railay Beach is famous for its limestone cliffs and rock climbing. Take a boat to the stunning Hong Islands or snorkel in the crystal-clear waters of Koh Phi Phi. Visit the Emerald Pool, climb 1,237 steps to Tiger Cave Temple, or relax at Ao Nang Beach.",
      "iaco": "VTSG",
      "iata": "KBV",
      "id": "kra_kbv",
      "img": "https://images.unsplash.com/photo-1596879857570-7b6b9018bcb6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "8.0863",
      "longitude": "98.9063",
      "temperature": "hot",
      "type": "beach"
    },
    "koh_usm": {
      "airport": "Samui International Airport",
      "average_cost": "luxury",
      "best_season": "summer",
      "city": "Koh Samui",
      "counter": 0,
      "country": "Thailand",
      "description": "Koh Samui is a tropical island known for its luxurious resorts and lively atmosphere. Relax at Chaweng Beach, explore the mystical Big Buddha Temple, and visit the famous Grandfather & Grandmother Rocks. Take a boat trip to Ang Thong National Marine Park for kayaking and snorkeling. Enjoy beachside nightlife and seafood at Fisherman’s Village.",
      "iaco": "VTSM",
      "iata": "USM",
      "id": "koh_usm",
      "img": "https://images.unsplash.com/photo-1564030915877-c65e6e6a1247?q=80&w=3165&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "9.5120",
      "longitude": "100.0138",
      "temperature": "hot",
      "type": "island"
    },
    "pat_pxt": {
      "airport": "Trat Airport",
      "average_cost": "budget",
      "best_season": "summer",
      "city": "Pattaya",
      "counter": 0,
      "country": "Thailand",
      "description": "Pattaya is a city famous for its lively beaches, vibrant nightlife, and cultural attractions. Visit the Sanctuary of Truth, an intricate wooden temple, and relax at Jomtien Beach. Take a trip to Coral Island (Koh Larn) for snorkeling, or visit Nong Nooch Tropical Garden for its stunning landscape. Pattaya also offers exciting nightlife along Walking Street.",
      "iaco": "VTBO",
      "iata": "PXT",
      "id": "pat_pxt",
      "img": "https://images.unsplash.com/photo-1625492206717-61c584a8b11e?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "12.9236",
      "longitude": "100.8825",
      "temperature": "hot",
      "type": "beach"
    },
    "man_mnl": {
      "airport": "Ninoy Aquino International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Manila",
      "counter": 0,
      "country": "Philippines",
      "description": "Manila, the capital of the Philippines, is a bustling metropolis with a mix of colonial history and modern skyscrapers. Visit Intramuros, the historic walled city from the Spanish era, and explore Fort Santiago. Discover Filipino culture at the National Museum, shop at Greenbelt or SM Mall of Asia, and enjoy sunset views along Manila Bay. For nightlife, head to Poblacion in Makati.",
      "iaco": "RPLL",
      "iata": "MNL",
      "id": "man_mnl",
      "img": "https://images.unsplash.com/photo-1598258710957-db8614c2881e?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "14.5995",
      "longitude": "120.9842",
      "temperature": "hot",
      "type": "city"
    },
    "ceb_ceb": {
      "airport": "Mactan-Cebu International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Cebu",
      "counter": 0,
      "country": "Philippines",
      "description": "Cebu is a vibrant city with historical significance and beautiful beaches. Visit Magellan’s Cross, Basilica del Santo Niño, and Fort San Pedro. For adventure, go canyoneering in Kawasan Falls, dive with whale sharks in Oslob, or relax on Mactan Island’s beaches. The city also has a fantastic food scene, famous for its Lechon Cebu (roast pig).",
      "iaco": "RPVM",
      "iata": "CEB",
      "id": "ceb_ceb",
      "img": "https://images.unsplash.com/photo-1662120008178-2b0d3f7b7096?q=80&w=3024&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "10.3157",
      "longitude": "123.8854",
      "temperature": "hot",
      "type": "city"
    },
    "bor_mph": {
      "airport": "Godofredo P. Ramos Airport (Caticlan)",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Boracay",
      "counter": 0,
      "country": "Philippines",
      "description": "Boracay is a world-famous tropical paradise known for its powdery white sand and crystal-clear waters. Enjoy water activities like kite surfing, snorkeling, and parasailing. Visit Puka Beach for a quieter experience, take a sunset cruise, or experience the island’s lively nightlife at Station 2. Willy’s Rock and Mount Luho offer great photo spots.",
      "iaco": "RPVE",
      "iata": "MPH",
      "id": "bor_mph",
      "img": "https://images.unsplash.com/photo-1542213493895-edf5b94f5a96?q=80&w=3173&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "11.9674",
      "longitude": "121.9248",
      "temperature": "hot",
      "type": "beach"
    },
    "pue_pps": {
      "airport": "Puerto Princesa International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Puerto Princesa",
      "counter": 0,
      "country": "Philippines",
      "description": "Puerto Princesa is the gateway to Palawan’s stunning natural wonders. Visit the Puerto Princesa Underground River, one of the New 7 Wonders of Nature. Relax at Honda Bay’s islands, including Cowrie Island and Starfish Island. Enjoy fresh seafood at the Baywalk and explore the vibrant local markets.",
      "iaco": "RPVP",
      "iata": "PPS",
      "id": "pue_pps",
      "img": "https://images.unsplash.com/photo-1565191256290-c7267f032248?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "9.7392",
      "longitude": "118.7353",
      "temperature": "hot",
      "type": "beach"
    },
    "cor_usu": {
      "airport": "Francisco B. Reyes Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Coron",
      "counter": 0,
      "country": "Philippines",
      "description": "Coron is a paradise for divers and nature lovers. Explore the stunning limestone cliffs and crystal-clear waters of Kayangan Lake. Dive among WWII shipwrecks, snorkel at Twin Lagoon, and relax at Malcapuya Beach. Island hopping tours to Siete Pecados and Banana Island are a must.",
      "iaco": "RPVU",
      "iata": "USU",
      "id": "cor_usu",
      "img": "https://images.unsplash.com/photo-1593994603115-deaa40043bae?q=80&w=3164&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "11.9989",
      "longitude": "120.2086",
      "temperature": "hot",
      "type": "beach"
    },
    "ilo_ilo": {
      "airport": "Iloilo International Airport",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Iloilo",
      "counter": 0,
      "country": "Philippines",
      "description": "Iloilo is a city rich in heritage and gastronomy. Visit the UNESCO-listed Miagao Church, explore Calle Real’s colonial buildings, and relax at Molo Church. Enjoy La Paz Batchoy, a famous noodle soup, and take a boat trip to Guimaras Island, known for the world’s sweetest mangoes.",
      "iaco": "RPVI",
      "iata": "ILO",
      "id": "ilo_ilo",
      "img": "https://images.unsplash.com/photo-1598147853558-b53f7f671c0b?q=80&w=2223&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "10.7202",
      "longitude": "122.5625",
      "temperature": "hot",
      "type": "historical"
    },
    "dav_dvo": {
      "airport": "Francisco Bangoy International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Davao",
      "counter": 0,
      "country": "Philippines",
      "description": "Davao is home to Mount Apo, the highest peak in the Philippines. Visit the Philippine Eagle Center, explore Eden Nature Park, and relax at Samal Island’s pristine beaches. Don’t miss trying Durian, the ‘King of Fruits,’ and explore Davao’s night markets for local delicacies.",
      "iaco": "RPMD",
      "iata": "DVO",
      "id": "dav_dvo",
      "img": "https://images.unsplash.com/photo-1551334432-01340a95cce3?q=80&w=2969&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "7.1907",
      "longitude": "125.4553",
      "temperature": "hot",
      "type": "city"
    },
    "han_han": {
      "airport": "Noi Bai International Airport",
      "average_cost": "budget",
      "best_season": "autumn",
      "city": "Hanoi",
      "counter": 0,
      "country": "Vietnam",
      "description": "Hanoi, the capital of Vietnam, is a city of history, culture, and incredible street food. Explore the Old Quarter’s bustling streets, visit the iconic Hoan Kiem Lake and the Ngoc Son Temple, and learn about Vietnam’s history at the Ho Chi Minh Mausoleum and the Imperial Citadel of Thang Long. Don't miss the unique Water Puppet Theatre and the vibrant night markets. For food lovers, try Bun Cha, Pho, and Egg Coffee in a hidden café.",
      "iaco": "VVNB",
      "iata": "HAN",
      "id": "han_han",
      "img": "https://images.unsplash.com/photo-1509030450996-dd1a26dda07a?q=80&w=3023&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "21.0285",
      "longitude": "105.8542",
      "temperature": "moderate",
      "type": "city"
    },
    "hoc_sgn": {
      "airport": "Tan Son Nhat International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Ho Chi Minh City",
      "counter": 0,
      "country": "Vietnam",
      "description": "Formerly known as Saigon, Ho Chi Minh City is Vietnam’s economic hub and a mix of modern skyscrapers and French colonial buildings. Visit the War Remnants Museum, explore the Notre-Dame Cathedral Basilica of Saigon, and walk along Nguyen Hue Walking Street. Experience the vibrant Ben Thanh Market and take a boat tour through the Mekong Delta. Don't forget to try Banh Mi and Vietnamese iced coffee!",
      "iaco": "VVTS",
      "iata": "SGN",
      "id": "hoc_sgn",
      "img": "https://images.unsplash.com/photo-1602646994030-464f98de5e5c?q=80&w=3164&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "10.7769",
      "longitude": "106.7009",
      "temperature": "hot",
      "type": "city"
    },
    "dal_dli": {
      "airport": "Lien Khuong Airport",
      "average_cost": "mid",
      "best_season": "spring",
      "city": "Da Lat",
      "counter": 0,
      "country": "Vietnam",
      "description": "Da Lat, known as the 'City of Eternal Spring,' is a romantic mountain retreat with cool weather, flower gardens, and French colonial architecture. Visit the Crazy House, Bao Dai’s Summer Palace, and the beautiful Valley of Love. Take a boat ride on Tuyen Lam Lake, chase waterfalls like Elephant Falls and Pongour Falls, and explore coffee plantations for some of Vietnam’s best brews.",
      "iaco": "VVDL",
      "iata": "DLI",
      "id": "dal_dli",
      "img": "https://images.unsplash.com/photo-1552310065-aad9ebece999?q=80&w=2962&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "11.9404",
      "longitude": "108.4583",
      "temperature": "moderate",
      "type": "mountain"
    },
    "hai_hph": {
      "airport": "Cat Bi International Airport",
      "average_cost": "mid",
      "best_season": "autumn",
      "city": "Hai Phong",
      "counter": 0,
      "country": "Vietnam",
      "description": "Hai Phong is Vietnam’s main port city, known for its colonial architecture and easy access to Cat Ba Island and Halong Bay. Visit the Du Hang Pagoda, explore the flower-filled streets, and relax at Do Son Beach. Take a boat trip to Lan Ha Bay, a stunning alternative to Halong Bay, with fewer crowds but just as much beauty.",
      "iaco": "VVCI",
      "iata": "HPH",
      "id": "hai_hph",
      "img": "https://images.unsplash.com/photo-1570559120097-e6c3388329e6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "20.8449",
      "longitude": "106.6881",
      "temperature": "moderate",
      "type": "city"
    },
    "hue_hui": {
      "airport": "Phu Bai International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Hue",
      "counter": 0,
      "country": "Vietnam",
      "description": "Hue, the former imperial capital of Vietnam, is a UNESCO-listed city rich in history. Visit the Hue Imperial City and the Forbidden Purple City, cruise along the Perfume River, and explore the ancient Thien Mu Pagoda. Don't miss the royal tombs of emperors and try traditional Hue cuisine like Bun Bo Hue and Banh Beo.",
      "iaco": "VVPB",
      "iata": "HUI",
      "id": "hue_hui",
      "img": "https://images.unsplash.com/photo-1572551887368-450aa6d8346e?q=80&w=2952&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "16.4637",
      "longitude": "107.5909",
      "temperature": "moderate",
      "type": "historical"
    },
    "dan_dad": {
      "airport": "Da Nang International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Da Nang",
      "counter": 0,
      "country": "Vietnam",
      "description": "Da Nang is a coastal city with a mix of modern attractions and natural beauty. Visit the Golden Bridge held by giant stone hands, explore the Marble Mountains, and relax at My Khe Beach. Take a day trip to Ba Na Hills for incredible views and an amusement park experience. At night, watch the Dragon Bridge breathe fire over the Han River.",
      "iaco": "VVDN",
      "iata": "DAD",
      "id": "dan_dad",
      "img": "https://images.unsplash.com/photo-1603852452378-a4e8d84324a2?q=80&w=2954&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "16.0544",
      "longitude": "108.2022",
      "temperature": "hot",
      "type": "beach"
    },
    "hoi_hia": {
      "airport": "Closest: Da Nang International Airport",
      "average_cost": "mid",
      "best_season": "autumn",
      "city": "Hoi An",
      "counter": 0,
      "country": "Vietnam",
      "description": "Hoi An is a beautifully preserved ancient town and UNESCO World Heritage Site. Walk through lantern-lit streets, take a boat ride along the Thu Bon River, and explore the Japanese Covered Bridge. Visit tailor shops for custom-made clothes and relax at An Bang Beach. Try Cao Lau, a famous Hoi An noodle dish.",
      "iaco": "VVHA",
      "iata": "HIA",
      "id": "hoi_hia",
      "img": "https://plus.unsplash.com/premium_photo-1690960644375-6f2399a08ebc?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "15.8801",
      "longitude": "108.3380",
      "temperature": "moderate",
      "type": "historical"
    },
    "nha_nha": {
      "airport": "Cam Ranh International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Nha Trang",
      "counter": 0,
      "country": "Vietnam",
      "description": "Nha Trang is Vietnam’s top beach destination, famous for its long coastline, vibrant nightlife, and diving spots. Visit Vinpearl Land for amusement park fun, explore the Po Nagar Cham Towers, and relax in the Thap Ba hot springs. Island-hopping tours take you to Hon Mun and Hon Tam islands.",
      "iaco": "VVCR",
      "iata": "NHA",
      "id": "nha_nha",
      "img": "https://images.unsplash.com/photo-1533002832-1721d16b4bb9?q=80&w=3078&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "12.2388",
      "longitude": "109.1966",
      "temperature": "hot",
      "type": "beach"
    },
    "sin_sin": {
      "airport": "Singapore Changi Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Singapore",
      "counter": 0,
      "country": "Singapore",
      "description": "Singapore, a futuristic city-state, is known for its skyscrapers, cultural diversity, and world-class attractions. Explore Marina Bay Sands for breathtaking views, visit Gardens by the Bay to witness the Supertree Grove, and shop along Orchard Road. Discover history in Chinatown, Little India, and Kampong Glam. Visit Sentosa Island for theme parks, beaches, and Universal Studios Singapore. Enjoy the vibrant hawker culture by trying Hainanese Chicken Rice, Chili Crab, and Laksa.",
      "iaco": "WSSS",
      "iata": "SIN",
      "id": "sin_sin",
      "img": "https://images.unsplash.com/photo-1508964942454-1a56651d54ac?q=80&w=2913&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "1.3521",
      "longitude": "103.8198",
      "temperature": "hot",
      "type": "city"
    },
    "sen_snt": {
      "airport": "Closest: Singapore Changi Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Sentosa",
      "counter": 0,
      "country": "Singapore",
      "description": "Sentosa Island is Singapore’s top leisure destination, home to golden beaches, luxury resorts, and world-famous attractions. Visit Universal Studios Singapore for thrilling rides, explore S.E.A. Aquarium, and take the Skyline Luge down a scenic track. Adventure seekers can try indoor skydiving at iFly or enjoy water sports at Siloso Beach. The island also has a vibrant nightlife scene, with beach clubs and fine dining options.",
      "iaco": "N/A",
      "iata": "SNT",
      "id": "sen_snt",
      "img": "https://images.unsplash.com/photo-1540086916044-196dc42d62c0?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "latitude": "1.2494",
      "longitude": "103.8303",
      "temperature": "hot",
      "type": "island"
    }
}

// 🔹 Function to add destinations
export default async function uploadDestinations () {
  try {
    const destinationsCollection = collection(db, "destinations");

    for (const key in destinationsData) {
      const destination = destinationsData[key];

      // Add each destination using its ID as the document ID
      await setDoc(doc(destinationsCollection, destination.id), destination);
      console.log(`Added: ${destination.city}`);
    }

    console.log("✅ All destinations added successfully!");
  } catch (error) {
    console.error("❌ Error uploading destinations: ", error);
  }
};

