import { db } from "./firebase"; // Import Firestore instance
import { collection, setDoc, doc } from "firebase/firestore";

const destinationsData= {
  "bue_eze": {
      "airport": "Ministro Pistarini International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Buenos Aires",
      "counter": 0,
      "country": "Argentina",
      "description": "Buenos Aires, Argentina's vibrant capital, is known for its European-style architecture, lively tango scene, and world-class cuisine. Walk through the colorful streets of La Boca, experience the energy of Plaza de Mayo, and indulge in delicious Argentine steak. Don't miss a football match at La Bombonera or a stroll in the historic San Telmo district.",
      "iaco": "SAEZ",
      "iata": "EZE",
      "id": "bue_eze",
      "img": "https://images.unsplash.com/photo-1569781845457-6bf89a3fce29",
      "latitude": "-34.6037",
      "longitude": "-58.3816",
      "temperature": "moderate",
      "type": "city"
    },
    "bar_brc": {
      "airport": "San Carlos de Bariloche Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Bariloche",
      "counter": 0,
      "country": "Argentina",
      "description": "Surrounded by the stunning Andes Mountains, Bariloche is a paradise for nature lovers and adventure seekers. Visit Nahuel Huapi National Park for breathtaking hikes, go skiing in Cerro Catedral, or explore the scenic Circuito Chico drive. Bariloche is also famous for its Swiss-style chocolate and alpine charm.",
      "iaco": "SAZS",
      "iata": "BRC",
      "id": "brc_brc",
      "img": "https://images.unsplash.com/photo-1584124694363-80174dc012ac",
      "latitude": "-41.1335",
      "longitude": "-71.3103",
      "temperature": "cold",
      "type": "mountain"
    },
    "ush_ush": {
      "airport": "Ushuaia – Malvinas Argentinas International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Ushuaia",
      "counter": 0,
      "country": "Argentina",
      "description": "The southernmost city in the world, Ushuaia is a gateway to Antarctica and a dream destination for adventure lovers. Explore Tierra del Fuego National Park, take a boat tour to see penguins on Martillo Island, and hike the breathtaking trails of Laguna Esmeralda. Ushuaia is also famous for its stunning snowy landscapes and thrilling winter sports.",
      "iaco": "SAWH",
      "iata": "USH",
      "id": "usu_ush",
      "img": "https://images.unsplash.com/photo-1571936122452-2706b92b3210",
      "latitude": "-54.8019",
      "longitude": "-68.3029",
      "temperature": "cold",
      "type": "snowy"
    },
    "men_mdz": {
      "airport": "Governor Francisco Gabrielli International Airport",
      "average_cost": "mid",
      "best_season": "autumn",
      "city": "Mendoza",
      "counter": 0,
      "country": "Argentina",
      "description": "Mendoza is Argentina’s wine country, known for its world-class Malbec vineyards and stunning Andean scenery. Take a wine tour in the Uco Valley, go white-water rafting in the Mendoza River, or hike Aconcagua, the highest peak in South America. Mendoza offers a perfect blend of relaxation, adventure, and gastronomy.",
      "iaco": "SAME",
      "iata": "MDZ",
      "id": "mdz_mdz",
      "img": "https://images.unsplash.com/photo-1623255194814-6f30a2c174b0",
      "latitude": "-32.8895",
      "longitude": "-68.8458",
      "temperature": "moderate",
      "type": "city"
    },
    "yer_evn": {
      "airport": "Zvartnots International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Yerevan",
      "counter": 0,
      "country": "Armenia",
      "description": "Yerevan, Armenia’s capital, is one of the world’s oldest continuously inhabited cities. Wander through Republic Square, visit the stunning Cascade Complex, and explore the ancient ruins of Erebuni Fortress. Yerevan is also a paradise for food lovers, offering delicious Armenian cuisine like khorovats (BBQ) and lavash bread. Don't forget to take in the view of Mount Ararat from the city!",
      "iaco": "UDYZ",
      "iata": "EVN",
      "id": "evn_evn",
      "img": "https://images.unsplash.com/photo-1605692561667-ea2482a2c23d",
      "latitude": "40.1792",
      "longitude": "44.4991",
      "temperature": "moderate",
      "type": "city"
    },
    "gyu_lwn": {
      "airport": "Shirak International Airport",
      "average_cost": "budget",
      "best_season": "autumn",
      "city": "Gyumri",
      "counter": 0,
      "country": "Armenia",
      "description": "Gyumri, Armenia’s second-largest city, is famous for its rich history and stunning architecture. Explore the Black Fortress, visit the historic Kumayri district, and enjoy the city's artistic atmosphere. Gyumri is also a hub for traditional Armenian crafts, offering a glimpse into the country’s cultural heritage.",
      "iaco": "UDSG",
      "iata": "LWN",
      "id": "gyu_gyu",
      "img": "https://images.unsplash.com/photo-1617110808975-d42506d44c2b",
      "latitude": "40.7894",
      "longitude": "43.8476",
      "temperature": "cold",
      "type": "historical"
    },
    "tav_evn": {
      "airport": "Zvartnots International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Tavush",
      "counter": 0,
      "country": "Armenia",
      "description": "Tavush is a hidden gem in Armenia, filled with lush forests, serene monasteries, and breathtaking mountain views. Hike through Dilijan National Park, explore the centuries-old Haghartsin Monastery, or relax by Parz Lake. Tavush is the perfect destination for nature lovers seeking tranquility and adventure.",
      "iaco": "UDYZ",
      "iata": "EVN",
      "id": "tav_tav",
      "img": "https://images.unsplash.com/photo-1591638610237-f9aa5fbbff8b",
      "latitude": "40.9645",
      "longitude": "45.1469",
      "temperature": "moderate",
      "type": "forest"
    },
    "syd_syd": {
      "airport": "Sydney Kingsford Smith Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Sydney",
      "counter": 0,
      "country": "Australia",
      "description": "Sydney is a vibrant city known for its iconic landmarks, stunning beaches, and world-class dining. Visit the Sydney Opera House and Harbour Bridge for breathtaking views, relax on the golden sands of Bondi Beach, or explore the historic Rocks district. Take a ferry to Manly Beach, hike in the Blue Mountains, and experience Sydney’s lively nightlife at Darling Harbour.",
      "iaco": "YSSY",
      "iata": "SYD",
      "id": "syd_syd",
      "img": "https://images.unsplash.com/photo-1506973035872-a4c27e4d6d36",
      "latitude": "-33.8688",
      "longitude": "151.2093",
      "temperature": "moderate",
      "type": "city"
    },
    "mel_mel": {
      "airport": "Melbourne Tullamarine Airport",
      "average_cost": "mid",
      "best_season": "autumn",
      "city": "Melbourne",
      "counter": 0,
      "country": "Australia",
      "description": "Melbourne is a cultural hub with a thriving arts scene, delicious coffee, and vibrant street art. Explore Federation Square, visit the National Gallery of Victoria, and take a stroll through the Royal Botanic Gardens. Ride the famous trams, enjoy live music in Fitzroy, or drive along the scenic Great Ocean Road for breathtaking coastal views.",
      "iaco": "YMML",
      "iata": "MEL",
      "id": "mel_mel",
      "img": "https://images.unsplash.com/photo-1567359389169-92cfc1e23b7e",
      "latitude": "-37.8136",
      "longitude": "144.9631",
      "temperature": "moderate",
      "type": "city"
    },
    "cns_cns": {
      "airport": "Cairns Airport",
      "average_cost": "mid",
      "best_season": "spring",
      "city": "Cairns",
      "counter": 0,
      "country": "Australia",
      "description": "Cairns is the gateway to the Great Barrier Reef, offering incredible snorkeling and diving experiences. Explore the lush Daintree Rainforest, take a scenic railway to Kuranda, or relax in the picturesque Palm Cove. Cairns is a paradise for adventure seekers with bungee jumping, white-water rafting, and helicopter tours over the reef.",
      "iaco": "YBCS",
      "iata": "CNS",
      "id": "cns_cns",
      "img": "https://images.unsplash.com/photo-1573199435357-f29b72d29829",
      "latitude": "-16.9203",
      "longitude": "145.7710",
      "temperature": "hot",
      "type": "beach"
    },
    "per_per": {
      "airport": "Perth Airport",
      "average_cost": "mid",
      "best_season": "spring",
      "city": "Perth",
      "counter": 0,
      "country": "Australia",
      "description": "Perth is a laid-back city with stunning beaches and a vibrant waterfront. Relax at Cottesloe Beach, visit Kings Park for amazing city views, and explore the historic port city of Fremantle. Take a ferry to Rottnest Island to see the adorable quokkas, and enjoy Swan Valley’s wine-tasting tours.",
      "iaco": "YPPH",
      "iata": "PER",
      "id": "per_per",
      "img": "https://images.unsplash.com/photo-1526470363-1580bc10f8ef",
      "latitude": "-31.9505",
      "longitude": "115.8605",
      "temperature": "hot",
      "type": "city"
    },
    "hob_hba": {
      "airport": "Hobart International Airport",
      "average_cost": "budget",
      "best_season": "summer",
      "city": "Hobart",
      "counter": 0,
      "country": "Australia",
      "description": "Hobart, the capital of Tasmania, is a charming city surrounded by natural beauty. Visit the famous MONA museum, explore Salamanca Market, and take a trip to Port Arthur’s historic site. Climb Mount Wellington for panoramic views and enjoy fresh seafood at Constitution Dock.",
      "iaco": "YMHB",
      "iata": "HBA",
      "id": "hob_hba",
      "img": "https://images.unsplash.com/photo-1566150914585-e0b2c5474ebd",
      "latitude": "-42.8821",
      "longitude": "147.3272",
      "temperature": "cold",
      "type": "city"
    },
    "vie_vie": {
      "airport": "Vienna International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Vienna",
      "counter": 0,
      "country": "Austria",
      "description": "Vienna, Austria’s capital, is a city of imperial history and cultural richness. Visit Schönbrunn Palace, explore the historic St. Stephen’s Cathedral, and enjoy classical music at the Vienna State Opera. Take a coffee break at one of Vienna’s famous cafés and stroll through the beautiful Prater Park.",
      "iaco": "LOWW",
      "iata": "VIE",
      "id": "vie_vie",
      "img": "https://images.unsplash.com/photo-1533907632021-503c4f3c150a",
      "latitude": "48.2082",
      "longitude": "16.3738",
      "temperature": "cold",
      "type": "city"
    },
    "sal_szg": {
      "airport": "Salzburg Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Salzburg",
      "counter": 0,
      "country": "Austria",
      "description": "Salzburg is the birthplace of Mozart and a city filled with baroque architecture. Explore the historic Altstadt (Old Town), visit Hohensalzburg Fortress, and tour the famous Mirabell Gardens. The city is also a gateway to the stunning Austrian Alps, perfect for skiing and hiking.",
      "iaco": "LOWS",
      "iata": "SZG",
      "id": "sal_szg",
      "img": "https://images.unsplash.com/photo-1512288094938-363287817259",
      "latitude": "47.8095",
      "longitude": "13.0550",
      "temperature": "cold",
      "type": "snowy"
    },
    "inn_inn": {
      "airport": "Innsbruck Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Innsbruck",
      "counter": 0,
      "country": "Austria",
      "description": "Innsbruck is a winter wonderland surrounded by the Austrian Alps. It’s a top destination for skiing and snowboarding, with stunning slopes and cozy mountain lodges. Explore the historic Old Town, visit the Golden Roof, and take a cable car up Nordkette for breathtaking alpine views.",
      "iaco": "LOWI",
      "iata": "INN",
      "id": "inn_inn",
      "img": "https://images.unsplash.com/photo-1504817488600-969f3e6c162e",
      "latitude": "47.2682",
      "longitude": "11.3923",
      "temperature": "cold",
      "type": "snowy"
    },
    "bak_gyd": {
      "airport": "Heydar Aliyev International Airport",
      "average_cost": "mid",
      "best_season": "spring",
      "city": "Baku",
      "counter": 0,
      "country": "Azerbaijan",
      "description": "Baku, the capital of Azerbaijan, blends futuristic skyscrapers with ancient history. Explore the UNESCO-listed Old City (Icherisheher) with its medieval walls, the iconic Maiden Tower, and the Palace of the Shirvanshahs. Visit the Flame Towers for a dazzling night view and stroll along Baku Boulevard by the Caspian Sea. The futuristic Heydar Aliyev Center, designed by Zaha Hadid, is a must-see for architecture lovers. Gobustan National Park, just outside the city, features ancient petroglyphs and bubbling mud volcanoes.",
      "iaco": "UBBB",
      "iata": "GYD",
      "id": "bak_gyd",
      "img": "https://images.unsplash.com/photo-1577805947697-89d9d5c68c44",
      "latitude": "40.4093",
      "longitude": "49.8671",
      "temperature": "moderate",
      "type": "city"
    },
    "gab_gbb": {
      "airport": "Gabala International Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Gabala",
      "counter": 0,
      "country": "Azerbaijan",
      "description": "Gabala is a stunning mountain town known for its natural beauty, adventure activities, and historical ruins. The Tufandag Mountain Resort is perfect for skiing in winter and hiking in summer. Visit the Nohur Lake for a peaceful escape, or explore the Gabala Shooting Club for outdoor sports. Yeddi Gozel Waterfall and the ruins of ancient Caucasian Albania add a historical touch to this charming region.",
      "iaco": "UBBQ",
      "iata": "GBB",
      "id": "gab_gbb",
      "img": "https://images.unsplash.com/photo-1566302386611-552201c3cacf",
      "latitude": "40.9819",
      "longitude": "47.8453",
      "temperature": "moderate",
      "type": "mountain"
    },
    "sha_lzq": {
      "airport": "Lankaran International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Sheki",
      "counter": 0,
      "country": "Azerbaijan",
      "description": "Sheki is a historical gem of Azerbaijan, famous for its caravanserais, palaces, and traditional sweets. The Sheki Khan’s Palace is a masterpiece of Persian-style stained glass and intricate wooden carvings. Explore the cobbled streets filled with handicraft shops, visit the ancient Albanian Church in Kish, and enjoy the natural beauty of the surrounding Caucasus mountains.",
      "iaco": "UBBL",
      "iata": "LZQ",
      "id": "sha_lzq",
      "img": "https://images.unsplash.com/photo-1603305870418-8079c1c58b07",
      "latitude": "41.1911",
      "longitude": "47.1706",
      "temperature": "moderate",
      "type": "historical"
    },
    "nas_nas": {
      "airport": "Lynden Pindling International Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Nassau",
      "counter": 0,
      "country": "The Bahamas",
      "description": "Nassau, the capital of The Bahamas, is a tropical paradise with pristine beaches and vibrant culture. Visit Paradise Island for luxury resorts and the iconic Atlantis water park. Explore the colonial-era Fort Fincastle, stroll down Bay Street for duty-free shopping, or take a boat tour to the Exumas to swim with pigs. Junkanoo Beach and Blue Lagoon Island are perfect for relaxation, while Cable Beach offers high-end resorts and casinos.",
      "iaco": "MYNN",
      "iata": "NAS",
      "id": "nas_nas",
      "img": "https://images.unsplash.com/photo-1551887373-6edba6dacbb1",
      "latitude": "25.0343",
      "longitude": "-77.3963",
      "temperature": "hot",
      "type": "beach"
    },
    "gbi_fpo": {
      "airport": "Grand Bahama International Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Freeport",
      "counter": 0,
      "country": "The Bahamas",
      "description": "Freeport, on Grand Bahama Island, is known for its crystal-clear waters, underwater caves, and diverse marine life. Lucayan National Park features one of the world's longest underwater cave systems, while Port Lucaya Marketplace offers Bahamian crafts and live music. Taino Beach is perfect for swimming and water sports, and Dolphin Encounter allows visitors to interact with friendly dolphins.",
      "iaco": "MYGF",
      "iata": "FPO",
      "id": "gbi_fpo",
      "img": "https://images.unsplash.com/photo-1595681347740-fc85a1b9769a",
      "latitude": "26.5333",
      "longitude": "-78.7000",
      "temperature": "hot",
      "type": "beach"
    },
    "ele_elt": {
      "airport": "North Eleuthera Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Eleuthera",
      "counter": 0,
      "country": "The Bahamas",
      "description": "Eleuthera is one of the most picturesque islands in The Bahamas, known for its pink sand beaches and laid-back atmosphere. Visit the Glass Window Bridge, where the deep blue Atlantic meets the turquoise Caribbean. Relax on French Leave Beach, explore the Hatchet Bay Caves, or take a boat trip to Harbour Island to experience its charming colonial-style architecture.",
      "iaco": "MYEH",
      "iata": "ELT",
      "id": "ele_elt",
      "img": "https://images.unsplash.com/photo-1551887353-08f6d3390a7c",
      "latitude": "25.2012",
      "longitude": "-76.1616",
      "temperature": "hot",
      "type": "beach"
    },
    "bim_bim": {
      "airport": "South Bimini Airport",
      "average_cost": "luxury",
      "best_season": "winter",
      "city": "Bimini",
      "counter": 0,
      "country": "The Bahamas",
      "description": "Bimini is known for its fascinating legends, including the fabled Fountain of Youth. This small island chain offers world-class deep-sea fishing, vibrant coral reefs for snorkeling, and crystal-clear waters. The Bimini Road, an underwater rock formation, is rumored to be part of the lost city of Atlantis. Visit the Dolphin House Museum and take a boat ride to Honeymoon Harbour to see stingrays up close.",
      "iaco": "MYBS",
      "iata": "BIM",
      "id": "bim_bim",
      "img": "https://images.unsplash.com/photo-1562193495-1a2f6f6b570e",
      "latitude": "25.7250",
      "longitude": "-79.2975",
      "temperature": "hot",
      "type": "island"
    },
    "dha_dac": {
      "airport": "Hazrat Shahjalal International Airport",
      "average_cost": "budget",
      "best_season": "winter",
      "city": "Dhaka",
      "counter": 0,
      "country": "Bangladesh",
      "description": "Dhaka, the capital of Bangladesh, is a bustling megacity rich in history, culture, and vibrant street life. Visit Lalbagh Fort, a stunning Mughal-era fortress with a mosque and tombs. Explore Ahsan Manzil, the 'Pink Palace,' a museum showcasing the city's colonial past. Wander through Sadarghat, one of the world's busiest river ports, where you can take a boat ride on the Buriganga River. Visit the National Parliament House, designed by legendary architect Louis Kahn, and soak in the spiritual atmosphere at Star Mosque and Dhakeshwari Temple. For a taste of local life, explore the colorful markets of Old Dhaka and try authentic Bangladeshi street food like fuchka and biryani.",
      "iaco": "VGHS",
      "iata": "DAC",
      "id": "dha_dac",
      "img": "https://images.unsplash.com/photo-1567529850173-815747f06324",
      "latitude": "23.8103",
      "longitude": "90.4125",
      "temperature": "hot",
      "type": "city"
    },
    "cox_cxb": {
      "airport": "Cox’s Bazar Airport",
      "average_cost": "mid",
      "best_season": "winter",
      "city": "Cox’s Bazar",
      "counter": 0,
      "country": "Bangladesh",
      "description": "Cox’s Bazar boasts the longest unbroken sea beach in the world, stretching over 120 kilometers along the Bay of Bengal. Relax on the golden sands of Laboni Beach, visit the picturesque Himchari Waterfall, or take a boat trip to St. Martin’s Island, Bangladesh’s only coral island. The town is also a gateway to Inani Beach, where you can witness stunning sunset views. Enjoy fresh seafood at the local markets and explore the Burmese Market for handicrafts. If you're interested in marine life, visit the Marine Aquarium & Research Institute.",
      "iaco": "VGCB",
      "iata": "CXB",
      "id": "cox_cxb",
      "img": "https://images.unsplash.com/photo-1541281652611-bb1b3b03af12",
      "latitude": "21.4272",
      "longitude": "91.9710",
      "temperature": "hot",
      "type": "beach"
    },
    "syl_zyl": {
      "airport": "Osmani International Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Sylhet",
      "counter": 0,
      "country": "Bangladesh",
      "description": "Sylhet is a land of rolling tea gardens, crystal-clear rivers, and lush green hills. Visit the famous Ratargul Swamp Forest, the only freshwater swamp forest in Bangladesh, for a boat ride through stunning nature. Explore Jaflong, a picturesque valley on the India-Bangladesh border, known for its stone collection activities and scenic beauty. The Madhabkunda Waterfall, the tallest in Bangladesh, is a must-visit for nature lovers. Sylhet is also home to many Sufi shrines, including the shrine of Hazrat Shah Jalal, attracting thousands of pilgrims each year.",
      "iaco": "VGSY",
      "iata": "ZYL",
      "id": "syl_zyl",
      "img": "https://images.unsplash.com/photo-1586356990714-09b6e9f11e16",
      "latitude": "24.8978",
      "longitude": "91.8714",
      "temperature": "moderate",
      "type": "forest"
    },
    "min_msq": {
      "airport": "Minsk National Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Minsk",
      "counter": 0,
      "country": "Belarus",
      "description": "Minsk, the capital of Belarus, is a city of Soviet-era architecture, modern cafes, and beautiful parks. Start your visit at Independence Square, home to the impressive Government House and the Church of Saints Simon and Helena (Red Church). Walk down the elegant Nezavisimosti Avenue to see grand Stalinist buildings. Visit the National Library of Belarus for panoramic city views. In the Old Town, explore Trinity Hill and the beautiful Svislach River embankment. The Great Patriotic War Museum offers insight into Belarus’ WWII history. For a unique experience, visit the Island of Tears, a memorial dedicated to Belarusian soldiers. Enjoy the city’s vibrant nightlife and trendy cafes, especially along Zybitskaya Street.",
      "iaco": "UMMS",
      "iata": "MSQ",
      "id": "min_msq",
      "img": "https://images.unsplash.com/photo-1592229473871-5c8b3cf62b2f",
      "latitude": "53.9006",
      "longitude": "27.5590",
      "temperature": "moderate",
      "type": "city"
    },
    "mir_mir": {
      "airport": "Minsk National Airport",
      "average_cost": "budget",
      "best_season": "spring",
      "city": "Mir",
      "counter": 0,
      "country": "Belarus",
      "description": "Mir is famous for its stunning medieval Mir Castle, a UNESCO World Heritage site. The castle features Gothic, Baroque, and Renaissance architectural elements and offers guided tours showcasing its rich history. Walk through the scenic castle gardens, visit the nearby Chapel of St. Nicholas, and explore the charming streets of Mir. The town offers a glimpse into Belarusian history and is perfect for a day trip from Minsk.",
      "iaco": "UMMS",
      "iata": "MIR",
      "id": "mir_mir",
      "img": "https://images.unsplash.com/photo-1605976591244-009a50a2f860",
      "latitude": "53.4517",
      "longitude": "26.4722",
      "temperature": "moderate",
      "type": "historical"
    },
    "bre_bqt": {
      "airport": "Brest Airport",
      "average_cost": "mid",
      "best_season": "summer",
      "city": "Brest",
      "counter": 0,
      "country": "Belarus",
      "description": "Brest, a historic city near the Polish border, is known for the impressive Brest Fortress, a WWII memorial and museum dedicated to the heroic resistance of Soviet soldiers. Stroll along Sovetskaya Street, a lively pedestrian zone with cafes, shops, and street performers. Visit the unique Brest Railway Museum, displaying old Soviet locomotives. The Berestye Archaeological Museum showcases medieval wooden houses excavated from the area. For nature lovers, Belovezhskaya Pushcha National Park, home to European bison, is just outside the city.",
      "iaco": "UMBB",
      "iata": "BQT",
      "id": "brest_bqt",
      "img": "https://images.unsplash.com/photo-1625435968005-073a02cd2a8c",
      "latitude": "52.0976",
      "longitude": "23.7341",
      "temperature": "moderate",
      "type": "historical"
    }
}

// 🔹 Function to add destinations
export default async function uploadDestinations () {
  try {
    const destinationsCollection = collection(db, "destinations");

    for (const key in destinationsData) {
      const destination = destinationsData[key];

      // Add each destination using its ID as the document ID
      await setDoc(doc(destinationsCollection, destination.id), destination);
      console.log(`Added: ${destination.city}`);
    }

    console.log("✅ All destinations added successfully!");
  } catch (error) {
    console.error("❌ Error uploading destinations: ", error);
  }
};

