import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Time To Go!",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // Path to your favicon
    apple: "/logo.png", // For Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <Toaster position="top-center" />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
